In [148]:
#Import dependencies
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#Import data
csv_data = pd.read_csv("Resources/movie_metadata.csv", encoding="utf-8")
df = pd.DataFrame(csv_data)

In [149]:
df_count = df.count()

In [150]:
df_clean = df.dropna()

In [151]:
df_clean_count = df_clean.count()

In [152]:
df = df_clean
df.reset_index(drop=True)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,Color,Olivier Assayas,81.0,110.0,107.0,45.0,BÃ©atrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
3752,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
3753,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
3754,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
3755,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [153]:
df.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000

In [154]:
df.imdb_score.min(),df.imdb_score.max()

(1.6, 9.3)

In [155]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

# Exploratory Analysis

## Analysis of Directors and their IMDB Scores

This analysis

In [156]:

df.imdb_score.describe()

count    3756.000000
mean        6.465282
std         1.056247
min         1.600000
25%         5.900000
50%         6.600000
75%         7.200000
max         9.300000
Name: imdb_score, dtype: float64

In [157]:
#Create a dataframe of directors and imdb score for each movie
directors_and_imdb = pd.DataFrame(df[['director_name', 'imdb_score']])
directors_and_imdb

          director_name  imdb_score
0         James Cameron         7.9
1        Gore Verbinski         7.1
2            Sam Mendes         6.8
3     Christopher Nolan         8.5
5        Andrew Stanton         6.6
...                 ...         ...
5026    Olivier Assayas         6.9
5027       Jafar Panahi         7.5
5033      Shane Carruth         7.0
5035   Robert Rodriguez         6.9
5042           Jon Gunn         6.6

[3756 rows x 2 columns]

In [158]:
#Create a DataFrame of directors and IMDB Scores in which the score is above the average

directors_and_imdb_above_avg = directors_and_imdb[directors_and_imdb['imdb_score'] > 6.5]
directors_and_imdb_above_avg.reset_index(drop=True)

          director_name  imdb_score
0         James Cameron         7.9
1        Gore Verbinski         7.1
2            Sam Mendes         6.8
3     Christopher Nolan         8.5
4        Andrew Stanton         6.6
...                 ...         ...
1897    Olivier Assayas         6.9
1898       Jafar Panahi         7.5
1899      Shane Carruth         7.0
1900   Robert Rodriguez         6.9
1901           Jon Gunn         6.6

[1902 rows x 2 columns]

In [159]:
directors_and_imdb_above_avg_group = directors_and_imdb_above_avg.groupby('director_name').count()
directors_and_imdb_above_avg_group= directors_and_imdb_above_avg_group['imdb_score'].nlargest(30)
directors_and_imdb_above_avg_group

director_name
Steven Spielberg        22
Martin Scorsese         16
Clint Eastwood          15
Woody Allen             14
Ridley Scott            13
Peter Jackson           11
Robert Zemeckis         11
Richard Linklater       10
Steven Soderbergh       10
Tim Burton              10
Danny Boyle              9
David Fincher            9
John Carpenter           9
Ron Howard               9
Spike Lee                9
Chris Columbus           8
Christopher Nolan        8
Michael Bay              8
Oliver Stone             8
Quentin Tarantino        8
Rob Reiner               8
Sam Mendes               8
Ang Lee                  7
Barry Levinson           7
David O. Russell         7
Edward Zwick             7
Francis Ford Coppola     7
Guy Ritchie              7
James Cameron            7
James Wan                7
Name: imdb_score, dtype: int64

In [167]:
directors_and_imdb_above_avg_group = directors_and_imdb_above_avg.groupby('director_name').mean()
directors_above_avg_count = directors_and_imdb_above_avg_group['imdb_score'].nlargest(30)
directors_count = pd.DataFrame(directors_above_avg_count)
directors_count

                                  imdb_score
director_name
Irvin Kershner                      8.800000
Akira Kurosawa                      8.700000
Charles Chaplin                     8.600000
Tony Kaye                           8.600000
Alfred Hitchcock                    8.500000
Damien Chazelle                     8.500000
Florian Henckel von Donnersmarck    8.500000
Majid Majidi                        8.500000
Roger Allers                        8.500000
Ron Fricke                          8.500000
Sergio Leone                        8.433333
Christopher Nolan                   8.425000
Asghar Farhadi                      8.400000
Richard Marquand                    8.400000
Billy Wilder                        8.300000
Fritz Lang                          8.300000
Lee Unkrich                         8.300000
Lenny Abrahamson                    8.300000
Oliver Hirschbiegel                 8.300000
Pete Docter                         8.233333
Hayao Miyazaki                      8.225000
Quentin Tarantino                   8.200000
Elia Kazan                          8.200000
George Roy Hill                     8.200000
James McTeigue                      8.200000
Joshua Oppenheimer                  8.200000
Juan JosÃ© Campanella                8.200000
Victor Fleming                      8.150000
Milos Forman                        8.133333
David Sington                       8.100000

In [161]:
directors_and_imdb_above_avg_group = directors_and_imdb_above_avg.groupby('director_name').mean()
directors_above_avg_mean = directors_and_imdb_above_avg_group['imdb_score'].nlargest(30)
directors_score = pd.DataFrame(directors_above_avg_mean)

In [168]:
df_merge_director_imdb = pd.concat([directors_count, directors_score, on='director_name'])
df_merge_director_imdb

SyntaxError: invalid syntax (<ipython-input-168-525397bbb511>, line 1)

In [ ]:
#Create a group based on directors
directors_imdb_group = directors_and_imdb.groupby('director_name')

#Average imdb score per director
directors_avg_imdb = directors_imdb_group['imdb_score'].mean().nlargest(10)
directors_avg_imdb

In [ ]:
directors_and_imdb[directors_and_imdb['director_name']=='Akira Kurosawa']

In [ ]:
directors_and_imdb[directors_and_imdb['director_name']=='Charles Chaplin']

In [ ]:
#Create a group based on directors
directors_imdb_group = directors_and_imdb.groupby('director_name')

In [ ]:
#Average imdb score per director
directors_avg_imdb = directors_imdb_group['imdb_score'].mean().nlargest(10)
directors_avg_imdb

In [ ]:
directors_avg_imdb_chart = directors_avg_imdb.plot(kind='bar',figsize=(10,5))
directors_avg_imdb_chart